In [8]:
import pandas as pd
import nltk
from nltk import word_tokenize

In [9]:
sen="the food was best but the serving was worst"

In [13]:
import re
sen = [re.sub(r"[^a-zA-Z0-9]+", ' ', k) for k in sen.split("\n")]
print(sen)
sen2=sen

['the food was best but the serving was worst']

In [14]:
sen=word_tokenize(sen[0])

In [16]:
df=pd.DataFrame(sen,columns=['word'])
df['stopword']=0
df['pos_tag']=''

In [18]:
from nltk.corpus import stopwords
a=set(stopwords.words('english'))

In [19]:
df['word_len']=0

In [20]:
df

      word  stopword pos_tag  word_len
0      the         0                 0
1     food         0                 0
2      was         0                 0
3     best         0                 0
4      but         0                 0
5      the         0                 0
6  serving         0                 0
7      was         0                 0
8    worst         0                 0

[9 rows x 4 columns]

In [21]:
for i in range(0,len(df)):
    if (df['word'][i]) in a:
        df['stopword'][i]=1
        
        
    else:
        df['stopword'][i]=0
        
        
    if(len(df['word'][i])>3):
        df['word_len'][i]=1
    else:
        df['word_len'][i]=0

In [22]:
df

      word  stopword pos_tag  word_len
0      the         1                 0
1     food         0                 1
2      was         1                 0
3     best         0                 1
4      but         1                 0
5      the         1                 0
6  serving         0                 1
7      was         1                 0
8    worst         0                 1

[9 rows x 4 columns]

In [23]:
post_tag=nltk.pos_tag(sen
                     )

In [24]:
post_tag[0][1]

'DT'

In [25]:
df['pos_tag']=post_tag

In [28]:
next_l=[]
k=0
for i in range(0,len(sen)-1):
    #printi
    next_l.append(sen[i+1])

In [29]:
next_l

['food', 'was', 'best', 'but', 'the', 'serving', 'was', 'worst']

In [30]:
next_l.append("")

In [31]:
next_l

['food', 'was', 'best', 'but', 'the', 'serving', 'was', 'worst', '']

In [32]:
df['next_words']=""

In [33]:
df['next_words']=next_l

In [35]:
df['prev_words']=""
prev=[]

In [36]:
prev.append("")

In [38]:
for i in range(1,len(sen)):
    #print i
    #print sen[i]
    prev.append(sen[i-1])

In [39]:
prev

['', 'the', 'food', 'was', 'best', 'but', 'the', 'serving', 'was']

In [40]:
df['prev_words']=prev

In [41]:
df

      word  stopword        pos_tag  word_len next_words prev_words
0      the         1      (the, DT)         0       food
1     food         0     (food, NN)         1        was        the
2      was         1     (was, VBD)         0       best       food
3     best         0    (best, RBS)         1        but        was
4      but         1      (but, CC)         0        the       best
5      the         1      (the, DT)         0    serving        but
6  serving         0  (serving, NN)         1        was        the
7      was         1     (was, VBD)         0      worst    serving
8    worst         0    (worst, RB)         1                   was

[9 rows x 6 columns]

In [43]:
df['pre_word_tag']=""
df['post_word_tag']=""
print(sen)

['the', 'food', 'was', 'best', 'but', 'the', 'serving', 'was', 'worst']

In [45]:
import os
a=os.popen("echo '"+sen2[0]+"' > ~/stanford-parser-2012-11-12/stanfordtemp.txt")
parser_out = os.popen("~/stanford-parser-2012-11-12/lexparser.sh ~/stanford-parser-2012-11-12/stanfordtemp.txt")
print(parser_out)
for relation in parser_out:
    print(relation)

<os._wrap_close object at 0x7f15cbf2db00>
(ROOT

  (S

    (NP (DT the) (NN food))

    (VP (VBD was)

      (ADJP (JJS best))

      (SBAR (CC but)

        (S

          (NP (DT the) (NN serving))

          (VP (VBD was)

            (ADJP (JJS worst))))))))



det(food-2, the-1)

nsubj(best-4, food-2)

cop(best-4, was-3)

root(ROOT-0, best-4)

cc(worst-9, but-5)

det(serving-7, the-6)

nsubj(worst-9, serving-7)

cop(worst-9, was-8)

ccomp(best-4, worst-9)

In [47]:
from nltk.tree import Tree

examples = [ '(ROOT (S     (NP (DT the) (NN food))    (VP (VBD was) (ADJP (JJS best)) (SBAR (CC but) (S  (NP (DT the) (NN serving)) (VP (VBD was)       (ADJP (JJS worst))))))))']
head_word=[]

def find_noun_phrases(tree):
    return [subtree for subtree in tree.subtrees(lambda t: t.label()=='NP')]

def find_head_of_np(np):
    noun_tags = ['NN', 'NNS', 'NNP', 'NNPS']
    top_level_trees = [np[i] for i in range(len(np)) if type(np[i]) is Tree]
    ## search for a top-level noun
    top_level_nouns = [t for t in top_level_trees if t.label() in noun_tags]
    if len(top_level_nouns) > 0:
        ## if you find some, pick the rightmost one, just 'cause
        return top_level_nouns[-1][0]
    else:
        ## search for a top-level np
        top_level_nps = [t for t in top_level_trees if t.label()=='NP']
        if len(top_level_nps) > 0:
            ## if you find some, pick the head of the rightmost one, just 'cause
            return find_head_of_np(top_level_nps[-1])
        else:
            ## search for any noun
            nouns = [p[0] for p in np.pos() if p[1] in noun_tags]
            if len(nouns) > 0:
                ## if you find some, pick the rightmost one, just 'cause
                return nouns[-1]
            else:
                ## return the rightmost word, just 'cause
                return np.leaves()[-1]

for example in examples:
    tree = Tree.fromstring(example)
    for np in find_noun_phrases(tree):
       
        print(" ".join(np.leaves()))
        head = find_head_of_np(np)
        
        if head not in head_word:
            
            head_word.append(head)

the food
the serving

In [48]:
head_word

['food', 'serving']

In [78]:
df['head_word']=0
pos_pre=[]
pos_pre.append("")
pos_post=[]
pos=[]
df['pos']=""

for i in range(0,len(post_tag)-1):
    pos_post.append(post_tag[i+1][1])
pos_post.append("")

for i in range(0,len(post_tag)):
    pos.append(post_tag[i][1])
    
for i in range(1,len(post_tag)):
    pos_pre.append(post_tag[i-1][1])

df['pre_word_tag']=pos_pre
df['post_word_tag']=pos_post
df['pos']=pos

In [79]:
for i in range(0,len(df)):
   
        

    if (df['word'][i]) in head_word:
        print(df['word'][i])
        df['head_word'][i]=1
    else:
        df['head_word'][i]=0

food
serving

In [81]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag,pos
0,the,1,"(the, DT)",0,food,,,NN,0,the,0,2,,DT
1,food,0,"(food, NN)",1,was,the,DT,VBD,1,food,0,1,NN,NN
2,was,1,"(was, VBD)",0,best,food,NN,RBS,0,be,0,2,,VBD
3,best,0,"(best, RBS)",1,but,was,VBD,CC,0,best,0,1,,RBS
4,but,1,"(but, CC)",0,the,best,RBS,DT,0,but,0,1,,CC
5,the,1,"(the, DT)",0,serving,but,CC,NN,0,the,0,2,,DT
6,serving,0,"(serving, NN)",1,was,the,DT,VBD,1,serving,0,1,NN,NN
7,was,1,"(was, VBD)",0,worst,serving,NN,RB,0,be,0,2,,VBD
8,worst,0,"(worst, RB)",1,,was,VBD,,0,bad,0,1,,RB

In [82]:
t1="she is serving food in the restaurant"
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
  
    print(lemmatizer.lemmatize('worst','a'))

bad
bad
bad
bad
bad
bad
bad
bad
bad

In [83]:
from nltk.corpus import wordnet

morphy_tag = {'NN':wordnet.NOUN,'JJS':wordnet.ADJ,'VBD':wordnet.VERB,'RB':wordnet.ADJ,'VBG':wordnet.VERB}

In [84]:
morphy_tag

{'JJS': 'a', 'NN': 'n', 'RB': 'a', 'VBD': 'v', 'VBG': 'v'}

In [85]:
df['lematized_words']='NULL'
lema=[]
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
    c=post_tag[i][1]
    for name in morphy_tag.keys():
        if name == c:
            print(name)
            new=morphy_tag[name]
            print(new)
    lema.append(lemmatizer.lemmatize(post_tag[i][0],new))

NN
n
VBD
v
NN
n
VBD
v
RB
a

In [86]:
lema

['the', 'food', 'be', 'best', 'but', 'the', 'serving', 'be', 'bad']

In [87]:
df['lematized_words']=lema

In [88]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag,pos
0,the,1,"(the, DT)",0,food,,,NN,0,the,0,2,,DT
1,food,0,"(food, NN)",1,was,the,DT,VBD,1,food,0,1,NN,NN
2,was,1,"(was, VBD)",0,best,food,NN,RBS,0,be,0,2,,VBD
3,best,0,"(best, RBS)",1,but,was,VBD,CC,0,best,0,1,,RBS
4,but,1,"(but, CC)",0,the,best,RBS,DT,0,but,0,1,,CC
5,the,1,"(the, DT)",0,serving,but,CC,NN,0,the,0,2,,DT
6,serving,0,"(serving, NN)",1,was,the,DT,VBD,1,serving,0,1,NN,NN
7,was,1,"(was, VBD)",0,worst,serving,NN,RB,0,be,0,2,,VBD
8,worst,0,"(worst, RB)",1,,was,VBD,,0,bad,0,1,,RB

In [69]:
df['ortho_features']=''
for i in range(0,len(df)):
    if ((df['word'][i].istitle() == True) or (df['word'][i].isdigit()==True)):
        df['ortho_features'][i]=1
    else:
        df['ortho_features'][i]=0

In [71]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features
0,the,1,"(the, DT)",0,food,,,"(food, NN)",0,the,0
1,food,0,"(food, NN)",1,was,the,"(the, DT)","(was, VBD)",1,food,0
2,was,1,"(was, VBD)",0,best,food,"(food, NN)","(best, RBS)",0,be,0
3,best,0,"(best, RBS)",1,but,was,"(was, VBD)","(but, CC)",0,best,0
4,but,1,"(but, CC)",0,the,best,"(best, RBS)","(the, DT)",0,but,0
5,the,1,"(the, DT)",0,serving,but,"(but, CC)","(serving, NN)",0,the,0
6,serving,0,"(serving, NN)",1,was,the,"(the, DT)","(was, VBD)",1,serving,0
7,was,1,"(was, VBD)",0,worst,serving,"(serving, NN)","(worst, RB)",0,be,0
8,worst,0,"(worst, RB)",1,,was,"(was, VBD)",,0,bad,0

In [72]:
df['token_freq']=''
for i in range(0,len(df)):
    df['token_freq'][i]=sen.count(df['word'][i])

In [73]:
df['head_word_tag']=""
for i in range(0,len(post_tag)):
    
    if(post_tag[i][0] in head_word):
        df['head_word_tag'][i]=post_tag[i][1]

In [110]:
df.drop(['pos_tag'], axis=1)

,word,stopword,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag,pos
0,the,1,0,food,,,NN,0,the,0,2,,DT
1,food,0,1,was,the,DT,VBD,1,food,0,1,NN,NN
2,was,1,0,best,food,NN,RBS,0,be,0,2,,VBD
3,best,0,1,but,was,VBD,CC,0,best,0,1,,RBS
4,but,1,0,the,best,RBS,DT,0,but,0,1,,CC
5,the,1,0,serving,but,CC,NN,0,the,0,2,,DT
6,serving,0,1,was,the,DT,VBD,1,serving,0,1,NN,NN
7,was,1,0,worst,serving,NN,RB,0,be,0,2,,VBD
8,worst,0,1,,was,VBD,,0,bad,0,1,,RB

In [111]:
from sklearn.preprocessing import LabelEncoder
class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self # not relevant here

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

In [114]:
df.drop(['pos_tag'], axis=1)

,word,stopword,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag,pos
0,the,1,0,food,,,NN,0,the,0,2,,DT
1,food,0,1,was,the,DT,VBD,1,food,0,1,NN,NN
2,was,1,0,best,food,NN,RBS,0,be,0,2,,VBD
3,best,0,1,but,was,VBD,CC,0,best,0,1,,RBS
4,but,1,0,the,best,RBS,DT,0,but,0,1,,CC
5,the,1,0,serving,but,CC,NN,0,the,0,2,,DT
6,serving,0,1,was,the,DT,VBD,1,serving,0,1,NN,NN
7,was,1,0,worst,serving,NN,RB,0,be,0,2,,VBD
8,worst,0,1,,was,VBD,,0,bad,0,1,,RB

In [120]:
MultiColumnLabelEncoder(columns = ['word','next_words','prev_words','pre_word_tag','post_word_tag','lematized_words','head_word_tag','pos']).fit_transform(df)

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag,pos
0,4,1,"(the, DT)",0,3,0,0,3,0,6,0,2,0,1
1,2,0,"(food, NN)",1,6,5,2,6,1,4,0,1,1,2
2,5,1,"(was, VBD)",0,1,3,3,5,0,1,0,2,0,5
3,0,0,"(best, RBS)",1,2,6,5,1,0,2,0,1,0,4
4,1,1,"(but, CC)",0,5,1,4,2,0,3,0,1,0,0
5,4,1,"(the, DT)",0,4,2,1,3,0,6,0,2,0,1
6,3,0,"(serving, NN)",1,6,5,2,6,1,5,0,1,1,2
7,5,1,"(was, VBD)",0,7,4,3,4,0,1,0,2,0,5
8,6,0,"(worst, RB)",1,0,6,5,0,0,0,0,1,0,3

In [119]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag,pos
0,the,1,"(the, DT)",0,food,,,NN,0,the,0,2,,DT
1,food,0,"(food, NN)",1,was,the,DT,VBD,1,food,0,1,NN,NN
2,was,1,"(was, VBD)",0,best,food,NN,RBS,0,be,0,2,,VBD
3,best,0,"(best, RBS)",1,but,was,VBD,CC,0,best,0,1,,RBS
4,but,1,"(but, CC)",0,the,best,RBS,DT,0,but,0,1,,CC
5,the,1,"(the, DT)",0,serving,but,CC,NN,0,the,0,2,,DT
6,serving,0,"(serving, NN)",1,was,the,DT,VBD,1,serving,0,1,NN,NN
7,was,1,"(was, VBD)",0,worst,serving,NN,RB,0,be,0,2,,VBD
8,worst,0,"(worst, RB)",1,,was,VBD,,0,bad,0,1,,RB

In [118]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag,pos
0,the,1,"(the, DT)",0,food,,,NN,0,the,0,2,,DT
1,food,0,"(food, NN)",1,was,the,DT,VBD,1,food,0,1,NN,NN
2,was,1,"(was, VBD)",0,best,food,NN,RBS,0,be,0,2,,VBD
3,best,0,"(best, RBS)",1,but,was,VBD,CC,0,best,0,1,,RBS
4,but,1,"(but, CC)",0,the,best,RBS,DT,0,but,0,1,,CC
5,the,1,"(the, DT)",0,serving,but,CC,NN,0,the,0,2,,DT
6,serving,0,"(serving, NN)",1,was,the,DT,VBD,1,serving,0,1,NN,NN
7,was,1,"(was, VBD)",0,worst,serving,NN,RB,0,be,0,2,,VBD
8,worst,0,"(worst, RB)",1,,was,VBD,,0,bad,0,1,,RB